### ISSUE TITLE
<p>titi <br>tata</p> don't work

### ISSUE THREAD

**Issue by stephanedemotte** [Exilz/react-native-render-html#3]
`<br>` inside `<p></p>` don't work :)

**Comment by Exilz** [comment]
Sorry I completely missed this issue. You should implement a custom rendered to support `<br>`.
You could render a view with a little height, this should do the trick !

**Comment by jawinn** [comment]
What about replacing BRs within Text elements with `\n`?

**Comment by Exilz** [comment]
Well, you wouldn't have much control on it. I still think a custom renderer would be better for most cases.

**Comment by jawinn** [comment]
Thanks. This works and is what I ended up doing, for anyone else that may need:

```
const customRenderers = {
  br: (htmlAttribs, children, passProps) => {
    return (
      <Text style={passProps.htmlStyles.br} {...passProps}>{'\n'}</Text>
    )
  }
};
```

And usage. In my custom styles for `br`, I just have the `lineHeight` set.
`<HTML htmlStyles={YOURSTYLES} html={YOURHTML} renderers={customRenderers}/>`

**Comment by Exilz** [comment]
I guess I should add that to the default renderers, `<br>` is a rather common tag.

**Comment by phil-homecu** [comment]
I tried this fix and got the error `undefined is not an object (evaluating 'passProps.htmlStyles.br')`

**Comment by Exilz** [comment]
@phil-homecu please check out the `2.1.0` version
