### ISSUE TITLE
failing to import the Shallow Compare module

### ISSUE THREAD

**Issue by ofirgeller** [Exilz/react-native-render-html#4]
Using:

"react-native": "0.43.1",
"react": "16.0.0-alpha.6",
"react-native-render-html": "2.0.0",

After installing and running the android version of the app I got an exception in the packager because the module 'react-addons-shallow-compare' was not found.

`npm install react-addons-shallow-compare`

 Fixes the problem.

I can only guess that this module, that the docs now describe as legacy, used to be included with react but now needs to be installed separately with the use of React.PureComponent being the recommended way to achieve the same goal.

Quick fix: add react-addons-shallow-compare as a dependency
Proper fix: change to PureComponent

**Comment by Exilz** [comment]
Hi,
you're totally right. I'll try to upgrade to PureComponent ASAP, but please open a PR if you feel like doing it before I do.
